### PR TITLE
Bug/multiple device insertions

### LINKED ISSUE #115: IoTAManager does not handle multiple provisionings
Multiple device provisioning requests arriving to the IoTAManager with the protocol specified in the body (as opposed to those specifiying it in the query parameter chain) are not handled appropriately: just the last device is created.

### PR DESCRIPTION
**Pull request by dmoranj**
Fixes #115

### CODE REVIEW

File: lib/services/iotaRedirector.js [hunk 1]
```diff
@@ -162,8 +162,15 @@ function splitByProtocol(req) {
...
-            collections[req.body[collectionName][i].protocol][collectionName] = [_.clone(req.body[collectionName][i])];
+            if (collections[req.body[collectionName][i].protocol] &&
+                collections[req.body[collectionName][i].protocol][collectionName]) {
+                collections[req.body[collectionName][i].protocol][collectionName].push(
+                    _.clone(req.body[collectionName][i]));
+            } else {
+                collections[req.body[collectionName][i].protocol] = {};
+                collections[req.body[collectionName][i].protocol][collectionName] =
+                    [_.clone(req.body[collectionName][i])];
+            }
```
Comment (kzangeli) [inline lib/services/iotaRedirector.js]: So, if obj+arr already exist, push new item (cloned), else, create obj+array wuth new item (cloned).
Before this change, a second item removed the first, as it seems.
Just trying to understand ...

I imagine `push` works an an empty array also and this could be simplified, something like this:

```
if (!collections[req.body[collectionName][i].protocol] || !collections[req.body[collectionName][i].protocol][collectionName])
  {
    collections[req.body[collectionName][i].protocol] = {};
    collections[req.body[collectionName][i].protocol][collectionName] = [];
  }
  collections[req.body[collectionName][i].protocol][collectionName].push(_.clone(req.body[collectionName][i]));
```

[ Remember, I'm not familiar with node, neither expert in javascript ... ]

**Comment by jcanonav** [comment]
LGTM

File: test/unit/iotaRedirections-test.js [hunk 2]
```diff
@@ -273,6 +273,39 @@ describe('IoTA Redirections', function() {
         });
     });
 
+    describe('When the creation of multiple devices arrives to the manager', function() {
```
Comment (kzangeli) [inline test/unit/iotaRedirections-test.js]: In case this is used as documentation ...
  multiple devices arrives => multiple devices arrive

File: lib/services/iotaRedirector.js (hunk 1 above)
Comment (dmoranj) [inline lib/services/iotaRedirector.js]: Fixed in 9fd9344

The solution is not exactly the same, as it may be possible for the collections object to already have data while the array is unexistent.

Comment (kzangeli) [inline lib/services/iotaRedirector.js]: perfect

**Comment by kzangeli** [comment]
LGTM
