### PR TITLE
Task/accept protocol array

### LINKED ISSUE #17: Support multiple protocols in the `protocol` field
Current implementation fails when receiving payloads like the following one:
```
{
    "services": [
        {
            "attributes": [],
            "static_attributes": [],
            "apikey": "",
            "protocol": [
                "IoTA-JSON"
            ],
            "entity_type": "pruebasJson"
        }
    ]
}
```
This behavior seems to come from how the portal generates the protocol information (a combobox in this case). The IoT Manager should accept this kind of payload, transforming it to the common expression without the `[ ]` characters.

### PR DESCRIPTION
**Pull request by dmoranj**
Fix #17

### CODE REVIEW

**Comment by XavierVal** [comment]
LGTM

File: lib/services/iotaRedirector.js [hunk 1]
```diff
@@ -26,116 +26,211 @@
...
+        req.protocolObj = result;
+        next(error);
+    });
+}
+
+function splitByProtocol(req) {
+    var collectionName = guessCollection(req.body),
+        collections = {};
+
+    for (var i = 0; i < req.body[collectionName].length; i++) {
```
Comment (gtorodelvalle) [inline lib/services/iotaRedirector.js]: Since `guessCollection()` may return `null`, invoking `req.body[collectionName].length` may be problematic, doesn't it?

Comment (dmoranj) [inline lib/services/iotaRedirector.js]: It isn't, really, but the reason is somewhat obscure. If you see function `queryParamExtractor()`, you will see that it uses function `extractProtocols()` that in turn uses the previously mentioned function. If the return value of `guessCollection()` is null, so it will be the one for the `extractProtocols()` function, and the original function will raise an error, as you can see in line 75 of the same file.

Comment (gtorodelvalle) [inline lib/services/iotaRedirector.js]: NTC

**Comment by gtorodelvalle** [comment]
LGTM
